stages:
  training:
    cmd: python D:\Datascience\fullstackdsproject\src\DiamondPricePrediction\pipelines\training_pipeline.py
    deps:
      - D:\Datascience\fullstackdsproject\notebooks\data\gemstone.csv
      -  D:\Datascience\fullstackdsproject\artifacts\raw.csv
      - D:\Datascience\fullstackdsproject\src\DiamondPricePrediction\components\data_ingestion.py
      - D:\Datascience\fullstackdsproject\src\DiamondPricePrediction\components\data_transformation.py
      - D:\Datascience\fullstackdsproject\src\DiamondPricePrediction\components\model_trainer.py
      - D:\Datascience\fullstackdsproject\src\DiamondPricePrediction\components\model_evaluation.py
      
  #Behavior during dvc repro:
# Before re-running the stage (cmd:), DVC will remove the existing output files listed under outs: (if they exist).

    outs:
    # so dvc will delete and create the files so basically files will be deleted

    #  DVC ensures that the pipeline is reproducible and always reflects the latest outputs
      # - D:\Datascience\fullstackdsproject\artifacts\train.csv
      # - D:\Datascience\fullstackdsproject\artifacts\test.csv
      - D:\Datascience\fullstackdsproject\artifacts\LinearRegression().pkl # these canbe track better in mlflow
      - D:\Datascience\fullstackdsproject\artifacts\preprocessor.pkl # these canbe track better in mlflow
      - D:\Datascience\fullstackdsproject\artifacts\digshub_output_with_prediction.csv

